apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-checkin-dev
  namespace: tech-checkin-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-checkin-dev
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'tech-checkin-dev'
        vault.hashicorp.com/agent-inject-secret-tech-checkin-dev: 'dev/tech-checkin'
        vault.hashicorp.com/agent-inject-template-tech-checkin-dev: |
          {{- with secret "dev/tech-checkin" -}}
            export API_KEY="{{ .Data.data.API_KEY }}"
            export N8N_BASE_URL="{{ .Data.data.N8N_BASE_URL }}"
            export N8N_WORKFLOW_ID="{{ .Data.data.N8N_WORKFLOW_ID }}"
            export SMARTSHEET_ACCESS_TOKEN="{{ .Data.data.SMARTSHEET_ACCESS_TOKEN }}"
            export SMARTSHEET_REPORT_ID="{{ .Data.data.SMARTSHEET_REPORT_ID }}"
            export GEONAMES_USER="{{ .Data.data.GEONAMES_USER }}"
            export CRONJOB_24_CHECKS="{{ .Data.data.CRONJOB_24_CHECKS }}"
            export CRONJOB_1_CHECKS="{{ .Data.data.CRONJOB_1_CHECKS }}"
            export SMS_TOOL="{{ .Data.data.SMS_TOOL }}"
            export TEXTBELT_KEY="{{ .Data.data.TEXTBELT_KEY }}"
            export TEXTBELT_SENDER="{{ .Data.data.TEXTBELT_SENDER }}"
            export TWILIO_ACCOUNT_SID="{{ .Data.data.TWILIO_ACCOUNT_SID }}"
            export TWILIO_API_SID="{{ .Data.data.TWILIO_API_SID }}"
            export TWILIO_API_KEY="{{ .Data.data.TWILIO_API_KEY }}"
            export TWILIO_FROM="{{ .Data.data.TWILIO_FROM }}"
            export ADMIN_EMAIL="{{ .Data.data.ADMIN_EMAIL }}"
            export ADMIN_PHONE_NUMBER="{{ .Data.data.ADMIN_PHONE_NUMBER }}"
            export LOGGING_LEVEL="{{ .Data.data.LOGGING_LEVEL }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-almanac: 'dev/almanac'
        vault.hashicorp.com/agent-inject-template-almanac: |
          {{- with secret "dev/almanac" -}}
            export ALMANAC_API_KEY="{{ .Data.data.almanac_api_key }}"
            export AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN="{{ .Data.data.azure_devops_personal_access_token }}"
            export MICROSOFT_TEAMS_WEBHOOK_URL="{{ .Data.data.microsoft_teams_webhook_url }}"
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/ca-cert: /run/secrets/kubernetes.io/serviceaccount/ca.crt
      labels:
        app: tech-checkin-dev
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10014
        runAsGroup: 10015
      imagePullSecrets:
        - name: tech-checkin-registry-secret
      containers:
        - image: harbor.pscp-css.support/library/tech-checkin-dev:0.0.45
          imagePullPolicy: Always
          name: tech-checkin-dev
          command: ['sh', '-c', 'source /vault/secrets/tech-checkin-dev && source /vault/secrets/almanac && uvicorn CheckinAPI:checkin --host 0.0.0.0 --port 8000']
          ports:
            - containerPort: 8000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      initContainers:
        - name: almanac
          image: harbor.pscp-css.support/library/almanac:0.0.1
          restartPolicy: Always
          command: ['sh', '-c', 'source /vault/secrets/almanac && uvicorn almanac:app --host 0.0.0.0 --port 8444']
          ports:
            - containerPort: 8444
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      serviceAccountName: tech-checkin-dev
