apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: <Insert desired url endpoint Name>-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /<Insert desired url endpoint Name>